server:
  port: ${PORT:8000}

spring:
  application:
    name: api-gateway

api-gateway:
  resource-manager: ${RESOURCE_MANAGER:http://localhost:8002}
  task-manager: ${TASK_MANAGER:http://localhost:8001}